name: wac-core
version: @version@
author: Ninjoh
main: tk.martijn_heil.wac_core.WacCore
depend: [Factions]

permissions:
  wac-core.*:
    default: op
    description: Gives access to all wac-core permissions.
    children:
      wac-core.gamemode.spectator: true
      wac-core.command.sneak: true
      wac-core.command.sneak.others: true

  wac-core.gamemode.spectator:
    description: Allows you to enter spectator mode.
    default: op

  wac-core.command.sneak:
    description: Gives access to the /wac sneak command
    default: op

  wac-core.command.sneak.others:
    description: Allows you to edit other player's sneak status.
    default: op